# Generated by Django 3.0.8 on 2020-09-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
