# Generated by Django 3.0.8 on 2020-09-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_craeted',
            new_name='date_created',
        ),
    ]
