# Generated by Django 3.0.8 on 2020-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_pledges',
            field=models.IntegerField(default=0),
        ),
    ]
